steps:
- name: 'gcr.io/$PROJECT_ID/elixir-mix'
  env:  ['MIX_ENV=prod', 'BRUNCH_ENV=production']
  args: ['mix', 'deps.get']
- name: 'node:6.10'
  env:  ['MIX_ENV=prod', 'BRUNCH_ENV=production']
  args: ['/bin/bash', '-c', 'npm install; ./node_modules/brunch/bin/brunch b -p']
- name: 'gcr.io/$PROJECT_ID/elixir-mix'
  env:  ['MIX_ENV=prod', 'BRUNCH_ENV=production']
  args: ['/bin/bash', '-c', 'mix compile; mix phoenix.digest; mix release --env=prod']
- name: gcr.io/cloud-builders/gsutil
  entrypoint: '/bin/bash'
  args: ['cat _build/prod/rel/myapp/achives.txt | cp -I gs://backup-1yr.olr.zone/releases/myapp/']
